version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - 80:80
      - 443:443
  backend:
    container_name: backend
    build: ./backend
    expose:
      - "8000:8000"
    restart: always
  frontend:
    container_name: frontend
    depends_on:
      frontend-builder:
        condition: service_completed_successfully
    build: ./frontend/deploy-server
    volumes:
      - ./frontend/dist:/src/frontend
    expose:
      - "3000:3000"
    restart: always
  frontend-builder:
    container_name: frontend-builder
    depends_on:
      backend:
        condition: service_started
    build: ./frontend
    volumes:
      - ./frontend/dist:/src/dist