version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27018:27017"
    expose:
      - "27018"
    environment:
      MONGO_INITDB_DATABASE: exampleDB
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/db-data:/data/db