version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27019:27017"
    expose:
      - "27019"
    environment:
      MONGO_INITDB_DATABASE: exampleDB
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro